### ISSUE TITLE
Working with pre-release azure sdk?

### ISSUE THREAD

**Issue by Jaxwood** [microsoftarchive/wamo#6]
Hi,

Thank you for your work on this plugin!

Does this plugin work with the pre-release [azure sdk](https://github.com/Azure/azure-sdk-for-python/tree/v2.0.0rc6)?

I'm getting an error :  `AttributeError: 'module' object has no attribute 'WindowsAzureMissingResourceError'` using the plugin on Ubuntu 16.04.1 LTS and python v2.7.12

The command I'm using is the `check_azure_compute`.

Thanks!

**Comment by jeffmendoza** [comment]
Hi, this code is pretty old, and most likely only works with older versions of the azure sdk.

**Comment by Jaxwood** [comment]
Hi @jeffmendoza 

Thank you for your quick response. 

Do you remember which version of the Azure sdk you developed this against?

**Comment by Jaxwood** [comment]
Closing this - found out I need to use pre-1.0 release to make it work.
